//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace supermarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODECT
    {
        public int ID { get; set; }
        public string KIND { get; set; }
        public string NAMEE { get; set; }
        public Nullable<System.DateTime> DATEA { get; set; }
        public Nullable<System.DateTime> DATEE { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> AMOUNT { get; set; }
    }
}
